FROM apache/airflow:2.0.2
RUN pip install requests
RUN pip install pandas
RUN pip install sqlalchemy
RUN pip install psycopg2-binary
RUN pip install pymongo
RUN pip install pandasql
RUN pip install termcolor2
RUN pip install --no-cache-dir pymysql
RUN pip install  sshtunnel
RUN pip install marquez-python
RUN pip install marquez-airflow
RUN pip install pymysql
RUN pip install sshtunnel
RUN pip install pykeepass
RUN pip install swifter
RUN pip install python-dotenv
RUN pip install dwhutils==0.1.9
