FROM puckel/docker-airflow:1.10.9
RUN pip install requests
RUN pip install pandas
RUN pip install sqlalchemy
RUN pip install psycopg2-binary
RUN pip install pymongo
RUN pip install pandasql
RUN pip install termcolor2
RUN pip install --no-cache-dir pymysql