acct:
  tables:
    acct:
      fields:
        - 'account_id'
        - 'district_id'
        - 'frequency'
        - 'parseddate'
        - 'year'
        - 'month'
        - 'day'
      data_types:
        - 'str'
        - 'Int64'
        - 'str'
        - 'DATUM'
        - 'Int64'
        - 'Int64'
        - 'Int64'
      businesskeys:
        - 'account_id'
      layer: 'src'
      hash_key: 'acct_hk'
      table_type: 'satellit'