card:
  tables:
    card:
      fields:
        - 'card_id'
        - 'disp_id'
        - 'card_type'
        - 'year'
        - 'month'
        - 'day'
        - 'fulldate'
      data_types:
        - 'str'
        - 'str'
        - 'str'
        - 'Int64'
        - 'Int64'
        - 'Int64'
        - 'DATUM'
      businesskeys:
        - 'card_id'
      layer: 'src'
      hash_key: 'card_hk'
      table_type: 'satellit'

