cc_konto:
  tables:
    l_cc_konto:
      fields:
        - kreditkarte_hk
        - konto_hk
      businesskeys:
        - kreditkarte_hk
        - konto_hk
      layer: 'biz'
      hash_key: 'cc_konto_hk'
      table_type: 'link'
    l_m_cc_konto:
      fields:
        - rolle
        - kreditkarte_hk
        - konto_hk
      data_types:
        - 'str'
        - 'str'
        - 'str'
      businesskeys:
        - kreditkarte_hk
        - konto_hk
      layer: 'biz'
      hash_key: 'cc_konto_hk'
      table_type: 'satellit'
