client:
  tables:
    client:
      fields:
        - 'client_id'
        - 'sex'
        - 'fulldate'
        - 'day'
        - 'month'
        - 'year'
        - 'age'
        - 'social'
        - 'first'
        - 'middle'
        - 'last'
        - 'phone'
        - 'email'
        - 'address_1'
        - 'address_2'
        - 'city'
        - 'state'
        - 'zipcode'
        - 'district_id'
      businesskeys:
        - 'client_id'
      layer: 'src'
      hash_key: 'client_hk'
      table_type: 'satellit'