darlehen:
  tables:
    s_darlehen:
      fields:
        - 'darlehensnummer'
        - 'nominal'
        - 'startdatum'
        - 'enddatum'
        - 'status'
        - 'tilgung'
        - 'verwendungszweck'
        - 'futurecashflow'
        - 'loeschung'
      data_types:
        - 'str'
        - 'str'
        - 'str'
        - 'str'
        - 'str'
        - 'str'
        - 'str'
        - 'str'
        - 'str'
      businesskeys:
        - 'darlehensnummer'
      layer: 'biz'
      hash_key: 'darlehen_hk'
      table_type: 'satellit'
    h_darlehen:
      fields:
        - 'darlehensnummer'
      businesskeys:
        - 'darlehensnummer'
      layer: 'biz'
      hash_key: 'darlehen_hk'
      table_type: 'hub'