disposition:
  tables:
    disposition:
      fields:
        - 'disp_id'
        - 'client_id'
        - 'account_id'
        - 'user_type'
      data_types:
        - 'str'
        - 'str'
        - 'str'
        - 'str'
      businesskeys:
        - 'disp_id'
      layer: 'src'
      hash_key: 'disposition_hk'
      table_type: 'satellit'