district:
  tables:
    district:
      fields:
        - 'district_id'
        - 'city'
        - 'state_name'
        - 'state_abbrev'
        - 'region'
        - 'division'
      data_types:
        - 'Int64'
        - 'str'
        - 'str'
        - 'str'
        - 'str'
        - 'str'
      businesskeys:
         - 'district_id'
      layer: 'src'
      hash_key: 'district_hk'
      table_type: 'satellit'