geschaeftspartner:
  fields:
    - 'kundennummer'
    - 'anrede'
    - 'vorname'
    - 'nachname'
    - 'geburtsdatum'
    - 'sterbedatum'
    - 'geschlecht'
    - 'sozialversicherungsnummer'
    - 'kreditkartenanzahl'
    - 'loeschung'
  businesskeys:
    - 'kundennummer'
  layer: 'biz'
  hash_key: 'gp_hk'
  table_type: 'satellit'