gp_darlehen:
  tables:
    l_gp_darlehen:
      fields:
        - darlehen_hk
        - geschaeftspartner_hk
      businesskeys:
        - darlehen_hk
        - geschaeftspartner_hk
      layer: 'biz'
      hash_key: 'gp_darlehen_hk'
      table_type: 'link'
    l_s_gp_darlehen:
      fields:
        - darlehen_hk
        - geschaeftspartner_hk
      businesskeys:
        - darlehen_hk
        - geschaeftspartner_hk
      layer: 'biz'
      hash_key: 'gp_darlehen_hk'
      table_type: 'satellit'
