gp_konto:
  tables:
    l_gp_konto:
      fields:
        - geschaeftspartner_hk
        - konto_hk
      businesskeys:
        - geschaeftspartner_hk
        - konto_hk
      layer: 'biz'
      hash_key: 'gp_konto_hk'
      table_type: 'link'
    l_m_gp_konto:
      fields:
        - gp_rolle
        - geschaeftspartner_hk
        - konto_hk
      businesskeys:
        - geschaeftspartner_hk
        - konto_hk
      layer: 'biz'
      hash_key: 'gp_konto_hk'
      table_type: 'satellit'
