konto:
  tables:
    s_konto:
      fields:
        - 'kontonummer'
        - 'frequenz'
        - 'wertstellungszeitpunkt'
        - 'kontoerstellung_dt'
      data_types:
        - 'str'
        - 'str'
        - 'str'
        - 'str'
      businesskeys:
        - 'kontonummer'
      layer: 'biz'
      hash_key: 'konto_hk'
      table_type: 'satellit'
    h_konto:
      fields:
        - 'kontonummer'
      data_types:
        - 'str'
      businesskeys:
        - 'kontonummer'
      layer: 'biz'
      hash_key: 'konto_hk'
      table_type: 'hub'