loan:
  tables:
    loan:
      fields:
        - 'loan_id'
        - 'account_id'
        - 'amount'
        - 'duration'
        - 'payments'
        - 'status'
        - 'year'
        - 'month'
        - 'day'
        - 'fulldate'
        - 'location'
        - 'purpose'
      data_types:
        - 'str'
        - 'str'
        - 'Int64'
        - 'Int64'
        - 'Int64'
        - 'str'
        - 'Int64'
        - 'Int64'
        - 'Int64'
        - 'DATUM'
        - 'Int64'
        - 'str'
      businesskeys:
        - 'loan_id'
      layer: 'src'
      hash_key: 'loan_hk'
      table_type: 'satellit'