order:
  tables:
    order:
      fields:
        - 'order_id'
        - 'account_id'
        - 'bank_to'
        - 'account_to'
        - 'amount'
        - 'k_symbol'
      businesskeys:
        - 'order_id'
      layer: 'src'
      hash_key: 'order_hk'
      table_type: 'satellit'