trans:
  tables:
    trans:
      fields:
        - 'run_id'
        - 'trans_id'
        - 'account_id'
        - 'trans_type'
        - 'operation'
        - 'amount'
        - 'balance'
        - 'k_symbol'
        - 'bank'
        - 'account'
        - 'year'
        - 'month'
        - 'day'
        - 'fulldate'
        - 'fulltime'
        - 'fulldatewithtime'
      data_types:
        - 'Int64'
        - 'str'
        - 'str'
        - 'str'
        - 'str'
        - 'float64'
        - 'float64'
        - 'str'
        - 'str'
        - 'Int64'
        - 'Int64'
        - 'Int64'
        - 'Int64'
        - 'date'
        - 'time'
        - '%Y-%m-%dT%H:%M:%S'
      businesskeys:
        - 'trans_id'
      layer: 'src'
      hash_key: 'trans_hk'
      table_type: 'satellit'