trans:
  fields:
    - 'run_id'
    - 'trans_id'
    - 'account_id'
    - 'trans_type'
    - 'operation'
    - 'amount'
    - 'balance'
    - 'k_symbol'
    - 'bank'
    - 'account'
    - 'year'
    - 'month'
    - 'day'
    - 'fulldate'
    - 'fulltime'
    - 'fulldatewithtime'
  types:
    - 'Int64'
    - 'str'
    - 'str'
    - 'str'
    - 'str'
    - 'str'
    - 'str'
    - 'str'
    - 'str'
    - 'str'
    - 'Int64'
    - 'Int64'
    - 'Int64'
    - 'Date'
    - 'Datetime'
    - 'Datetime'
  businesskeys:
    - 'trans_id'
  layer: 'src'