database:
  CoreDWH:

    port: 3306 #5432
    db_name: CoreDWH
    host: 127.0.0.1  #VPN IP NAS
    type: mariadb # postgres
    sshhost: 82.165.203.114

    useSSH: False
    main: PoeticDrunkenCat
  MongoDB:
    port: 27017
    host: localhost
    db_name: PoeticDrunkenCat
  ARIMA_EXPORT:
    path: 'C:\Users\Public\EXPORTS'
    format: 'csv'
    