database:
  CoreDWH:
    port: 3306 #5432
    db_name: CoreDWH
    host: 192.168.178.33 #172.18.0.7
    type: mariadb # postgres
    sshhost: 82.165.203.114
    useSSH: False
    main: PoeticDrunkenCat
  MongoDB:
    port: 27017
    host: localhost
    db_name: PoeticDrunkenCat
  ARIMA_EXPORT:
    path: 'C:\Users\Public\EXPORTS'
    format: 'csv'
    